export enum AuthActionTypes {
  LOGIN_START = "[AUTH] LOGIN_START",
  LOGIN_SUCCESS = "[AUTH] LOGIN_SUCCESS",
  AUTHENTICATE_FAIL = "[AUTH] AUTHENTICATE_FAIL",
  SIGNUP_START = "[AUTH] SIGNUP_START",
  CLEAR_ERROR = "[AUTH] CLEAR_ERROR",
  LOGOUT = "[AUTH] LOGOUT",
  AUTO_LOGIN = "[AUTH] AUTO_LOGIN"
};

export enum ProjectsListTypes {
  FETCH_PROJECTS_START = "[PROJECTS LIST] FETCH_PROJECTS_START",
  FETCH_PROJECTS_SUCCESS = "[PROJECTS LIST] FETCH_PROJECTS_SUCCESS",
  FETCH_PROJECTS_FAIL = "[PROJECTS LIST] FETCH_PROJECTS_FAIL",
  JOIN_PROJECT_START = "[PROJECTS LIST] JOIN_PROJECT_START",
  JOIN_PROJECT_SUCCESS = "[PROJECTS LIST] JOIN_PROJECT_SUCCESS",
  JOIN_PROJECT_FAIL = "[PROJECTS LIST] JOIN_PROJECT_FAIL",
  JOIN_PROJECT_CLEAR_INFO = "[PROJECTS LIST] JOIN_PROJECT_CLEAR_INFO",
  CLEAR_INFO = "[PROJECTS LIST] CLEAR_INFO"
};

export enum ProjectActionTypes {
  FETCH_PROJECT_START = "[PROJECT] FETCH_PROJECT_START",
  FETCH_PROJECT_SUCCESS = "[PROJECT] FETCH_PROJECT_SUCCESS",
  FETCH_PROJECT_FAIL = "[PROJECT] FETCH_PROJECT_FAIL",
  CREATE_PROJECT_START = "[PROJECT] CREATE_PROJECT_START",
  CREATE_PROJECT_SUCCESS = "[PROJECT] CREATE_PROJECT_SUCCESS",
  CREATE_PROJECT_FAIL = "[PROJECT] CREATE_PROJECT_FAIL",
  UPDATE_PROJECT_START = "[PROJECT] UPDATE_PROJECT_START",
  UPDATE_PROJECT_SUCCESS = "[PROJECT] UPDATE_PROJECT_SUCCESS",
  UPDATE_PROJECT_FAIL = "[PROJECT] UPDATE_PROJECT_FAIL",
  DELETE_PROJECT_START = "[PROJECT] DELETE_PROJECT_START",
  DELETE_PROJECT_SUCCESS = "[PROJECT] DELETE_PROJECT_SUCCESS",
  DELETE_PROJECT_FAIL = "[PROJECT] DELETE_PROJECT_FAIL",
  LEAVE_PROJECT_START = "[PROJECT] LEAVE_PROJECT_START",
  LEAVE_PROJECT_SUCCESS = "[PROJECT] LEAVE_PROJECT_SUCCESS",
  LEAVE_PROJECT_FAIL = "[PROJECT] LEAVE_PROJECT_FAIL",
  CLEAR_PROJECT_INFO = "[PROJECT] CLEAR_PROJECT_INFO",
  CLEAR_ERROR = "[PROJECT] CLEAR_ERROR"
}

export enum AdminActionTypes {
  ACCEPT_USER_START = "[ADMIN] ACCEPT_USER_START",
  ACCEPT_USER_SUCCESS = "[ADMIN] ACCEPT_USER_SUCCESS",
  ACCEPT_USER_FAIL = "[ADMIN] ACCEPT_USER_FAIL",
  REJECT_USER_START = "[ADMIN] REJECT_USER_START",
  REJECT_USER_SUCCESS = "[ADMIN] REJECT_USER_SUCCESS",
  REJECT_USER_FAIL = "[ADMIN] REJECT_USER_FAIL",
}

export enum IterationActionTypes {
  CREATE_ITERATION_START = "[PROJECT] CREATE_ITERATION_START",
  CREATE_ITERATION_SUCCESS = "[PROJECT] CREATE_ITERATION_SUCCESS",
  CREATE_ITERATION_FAIL = "[PROJECT] CREATE_ITERATION_FAIL",
  UPDATE_ITERATION_START = "[PROJECT] UPDATE_ITERATION_START",
  UPDATE_ITERATION_SUCCESS = "[PROJECT] UPDATE_ITERATION_SUCCESS",
  UPDATE_ITERATION_FAIL = "[PROJECT] UPDATE_ITERATION_FAIL",
  DELETE_ITERATION_START = "[PROJECT] DELETE_ITERATION_START",
  DELETE_ITERATION_SUCCESS = "[PROJECT] DELETE_ITERATION_SUCCESS",
  DELETE_ITERATION_FAIL = "[PROJECT] DELETE_ITERATION_FAIL",
}

export enum TaskActionTypes {
  CREATE_TASK_START = "[PROJECT] CREATE_TASK_START",
  CREATE_TASK_SUCCESS = "[PROJECT] CREATE_TASK_SUCCESS",
  CREATE_TASK_FAIL = "[PROJECT] CREATE_TASK_FAIL",
  UPDATE_TASK_START = "[PROJECT] UPDATE_TASK_START",
  UPDATE_TASK_SUCCESS = "[PROJECT] UPDATE_TASK_SUCCESS",
  UPDATE_TASK_FAIL = "[PROJECT] UPDATE_TASK_FAIL",
  DELETE_TASK_START = "[PROJECT] DELETE_TASK_START",
  DELETE_TASK_SUCCESS = "[PROJECT] DELETE_TASK_SUCCESS",
  DELETE_TASK_FAIL = "[PROJECT] DELETE_TASK_FAIL",
  MOVE_TASK_START = "[PROJECT] MOVE_TASK_START",
  MOVE_TASK_SUCCESS = "[PROJECT] MOVE_TASK_SUCCESS",
  MOVE_TASK_FAIL = "[PROJECT] MOVE_TASK_FAIL"
}

export enum EditIterationTypes {
  OPEN_ITERATION_EDIT = "[EDIT ITERATION] OPEN_ITERATION_EDIT",
  CLOSE_ITERATION_EDIT = "[EDIT ITERATION] CLOSE_ITERATION_EDIT"
}

export enum EditProjectTypes {
  OPEN_PROJECT_EDIT = "[EDIT PROJECT] OPEN_PROJECT_EDIT",
  CLOSE_PROJECT_EDIT = "[EDIT PROJECT] CLOSE_PROJECT_EDIT"
}

export enum EditTaskTypes {
  OPEN_TASK_EDIT = "[EDIT TASK] OPEN_TASK_EDIT",
  CLOSE_TASK_EDIT = "[EDIT TASK] CLOSE_TASK_EDIT"
}